# Numpy Practice

## Load numpy

In [1]:
import numpy as np

## Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

##### Get Dimensions

In [4]:
a.ndim

1

In [5]:
b.ndim

2

##### Get Shape

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

##### Get Type

In [8]:
a.dtype

dtype('int32')

##### Get Size

In [9]:
a.itemsize

4

##### Get Total Size

In [10]:
a.nbytes

12

### Accessing or Changing specific elements, rows and columns

In [11]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
arr.shape

(2, 7)

##### Get a specific element [r, c]

In [13]:
# GET NUMBER 13
arr[1, 5]

13

##### Get Specific Row

In [14]:
# USE SLICE SYNTAX
arr[0, :]

array([1, 2, 3, 4, 5, 6, 7])

##### Get Specific Column

In [15]:
# USE SLICE SYNTAX
arr[:, 2]

array([ 3, 10])

##### Getting fancy [startindex:endindex:steps]

In [16]:
# IN FIRST ROW ONLY
arr[0, 1:6:2]

array([2, 4, 6])

##### 3D Example

In [17]:
three_dim = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
three_dim

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

##### Get Specific Element
Just play around with this.
Can use slice syntax too.

In [18]:
three_dim[0,1,1]

4

In [19]:
three_dim[:,0,:]

array([[1, 2],
       [5, 6]])

### Initializing Different Types of Arrays

##### All 0s Matrix

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

##### All 1s Matrix

In [23]:
np.ones(2)

array([1., 1.])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

##### Any other number

In [26]:
np.full((2,3), 56)

array([[56, 56, 56],
       [56, 56, 56]])

##### Any other number (full_like)

In [27]:
full_like_variable = np.array([[1,2,3],[4,5,6]])
full_like_variable

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.full_like(full_like_variable, 99)

array([[99, 99, 99],
       [99, 99, 99]])

##### Random Decimal Numbers

In [29]:
np.random.rand(2,4)

array([[0.26005261, 0.84135387, 0.24549859, 0.79162236],
       [0.79178143, 0.59631164, 0.05479239, 0.68508383]])

In [30]:
np.random.random_sample(full_like_variable.shape)

array([[0.47932141, 0.99714014, 0.19353685],
       [0.61860429, 0.29064682, 0.61139689]])

##### Random Integer Values

In [31]:
# It starts at 0 if not indicate the starting point
np.random.randint(5, size = (2,3))

array([[0, 4, 2],
       [3, 0, 0]])

In [32]:
np.random.randint(5,7, size = (2,2))

array([[6, 6],
       [5, 6]])

##### Identity Matrix

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Repeat an Array

In [38]:
# SHOULD BE 2D ARRAY
rep_arr = np.array([[1,2,3]])
repeat_array = np.repeat(rep_arr,3, axis=0)
repeat_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

##### Matrix Challenge

In [42]:
# FIRST, CREATE A ONES 5X5 ARRAY
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
zero[1,1] = 9
zero

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [47]:
output[1:-1, 1:-1] = zero
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Copying Array

In [48]:
# USE A COPY METHOD = "copy()"
array_a = np.array([1,2,3])
array_b = array_a.copy()
array_b

array([1, 2, 3])

### Mathematics

In [51]:
math_arr = np.array([1,2,3,4])
math_arr

array([1, 2, 3, 4])

In [53]:
math_arr + 2

array([3, 4, 5, 6])

In [54]:
math_arr - 2

array([-1,  0,  1,  2])

In [55]:
math_arr * 2

array([2, 4, 6, 8])

In [56]:
math_arr / 2

array([0.5, 1. , 1.5, 2. ])

In [58]:
math_arr ** 2

array([ 1,  4,  9, 16])

In [57]:
math_arr_1 = np.array([1,0,1,0])
math_arr + math_arr_1

array([2, 2, 4, 4])

##### Take the Sin

In [59]:
np.sin(math_arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Take the Cos

In [60]:
np.cos(math_arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [62]:
arr_1 = np.ones((2,3))
arr_1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
arr_2 = np.full((3,2), 2)
arr_2

array([[2, 2],
       [2, 2],
       [2, 2]])

In [66]:
# MATRIX MULTIPLY FUNCTION = "matmul()"
np.matmul(arr_1, arr_2)

array([[6., 6.],
       [6., 6.]])

##### Find the Determinant

In [67]:
arr_3 = np.identity(3)
np.linalg.det(arr_3)

1.0

### Statistics

In [68]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Get the Minimum Value

In [69]:
np.min(stats)

1

In [71]:
np.min(stats, axis = 0)

array([1, 2, 3, 4])

##### Get the Maximum value

In [70]:
np.max(stats)

8

In [72]:
np.max(stats, axis = 0)

array([5, 6, 7, 8])

###### Get the Sum

In [73]:
np.sum(stats)

36

In [74]:
np.sum(stats, axis=0)

array([ 6,  8, 10, 12])