# Numpy Practice

## Load numpy

In [1]:
import numpy as np

## Basics

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

##### Get Dimensions

In [7]:
a.ndim

1

In [8]:
b.ndim

2

##### Get Shape

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

##### Get Type

In [13]:
a.dtype

dtype('int32')

##### Get Size

In [14]:
a.itemsize

4

##### Get Total Size

In [15]:
a.nbytes

12

### Accessing or Changing specific elements, rows and columns

In [18]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
arr.shape

(2, 7)

##### Get a specific element [r, c]

In [24]:
# GET NUMBER 13
arr[1, 5]

13

##### Get Specific Row

In [26]:
# USE SLICE SYNTAX
arr[0, :]

array([1, 2, 3, 4, 5, 6, 7])

##### Get Specific Column

In [27]:
# USE SLICE SYNTAX
arr[:, 2]

array([ 3, 10])

##### Getting fancy [startindex:endindex:steps]

In [29]:
# IN FIRST ROW ONLY
arr[0, 1:6:2]

array([2, 4, 6])

##### 3D Example

In [30]:
three_dim = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
three_dim

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

##### Get Specific Element
Just play around with this.
Can use slice syntax too.

In [32]:
three_dim[0,1,1]

4

In [33]:
three_dim[:,0,:]

array([[1, 2],
       [5, 6]])

### Initializing Different Types of Arrays

##### All 0s Matrix

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

##### All 1s Matrix

In [37]:
np.ones(2)

array([1., 1.])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

##### Any other number

In [45]:
np.full((2,3), 56)

array([[56, 56, 56],
       [56, 56, 56]])

##### Any other number (full_like)

In [48]:
full_like_variable = np.array([[1,2,3],[4,5,6]])
full_like_variable

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.full_like(full_like_variable, 99)

array([[99, 99, 99],
       [99, 99, 99]])

##### Random Decimal Numbers

In [50]:
np.random.rand(2,4)

array([[0.52609603, 0.98814968, 0.58595242, 0.85654921],
       [0.74319859, 0.15679998, 0.98473295, 0.07657026]])

In [52]:
np.random.random_sample(full_like_variable.shape)

array([[0.8773021 , 0.92345474, 0.7651041 ],
       [0.5344289 , 0.70625696, 0.29655854]])

##### Random Integer Values

In [70]:
# It starts at 0 if not indicate the starting point
np.random.randint(5, size = (2,3))

array([[1, 2, 1],
       [3, 4, 4]])

In [69]:
np.random.randint(5,7, size = (2,2))

array([[6, 6],
       [5, 6]])

##### Identity Matrix

In [72]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])